# .github/workflows/release.yml

name: Create Plugin Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    name: Build for ${{ matrix.os_name }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            os_name: Linux
            platform_id: linux
            preset: release
            cmake_build_preset: release
            build_path: "build/release"
          - os: windows-latest
            os_name: Windows
            platform_id: windows
            preset: vs2022
            cmake_build_preset: vs2022-release
            build_path: "build/vs2022"
          - os: macos-latest
            os_name: macOS
            platform_id: macos
            preset: release
            cmake_build_preset: release
            build_path: "build/release"

    env:
      ZIP_NAME: "DSP-JUCE-Plugin-${{ github.ref_name }}-${{ matrix.platform_id }}.zip"
      ARTIFACT_DIR: "${{ matrix.build_path }}/DSPJucePlugin_artefacts/Release"

    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Linux dependencies
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libasound2-dev \
            libx11-dev \
            libxcomposite-dev \
            libxcursor-dev \
            libxinerama-dev \
            libxrandr-dev \
            libfreetype6-dev \
            libfontconfig1-dev \
            libgl1-mesa-dev \
            libwebkit2gtk-4.1-dev

      - name: Cache JUCE
        uses: actions/cache@v4
        id: cache-juce
        with:
          path: ${{ github.workspace }}/.juce_cache
          key: ${{ runner.os }}-juce-${{ hashFiles('**/CMakeLists.txt') }}

      - name: Configure CMake
        run: cmake --preset=${{ matrix.preset }} -DFETCHCONTENT_BASE_DIR=${{ github.workspace }}/.juce_cache

      - name: Build with CMake
        run: cmake --build ${{ matrix.build_path }} --config Release

      - name: Validate build artifacts
        run: bash scripts/validate-builds.sh Release
        shell: bash

      - name: Archive plugin artifacts
        shell: bash
        run: |
          cd "${{ env.ARTIFACT_DIR }}"
          if [ "${{ matrix.os }}" == "macos-latest" ]; then
            zip -r "${{ github.workspace }}/${{ env.ZIP_NAME }}" VST3 Standalone AU
          else
            zip -r "${{ github.workspace }}/${{ env.ZIP_NAME }}" VST3 Standalone
          fi

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.ZIP_NAME }}
          path: ${{ env.ZIP_NAME }}

  create_release:
    name: Create GitHub Release
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write # Required to create a release

    steps:
      - name: Download all build artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Create Release and Upload Assets
        uses: softprops/action-gh-release@v2
        with:
          files: artifacts/*/*.zip
          body: "Automated release for version ${{ github.ref_name }}."
          fail_on_unmatched_files: true
