# .github/workflows/release.yml

name: Create Plugin Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    name: Build for ${{ matrix.os_name }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            os_name: Linux
            platform_id: linux
            preset: release
            cmake_build_preset: release
            build_path: "build/release"
          - os: windows-latest
            os_name: Windows
            platform_id: windows
            preset: vs2022
            cmake_build_preset: vs2022-release
            build_path: "build/vs2022"
          - os: macos-latest
            os_name: macOS
            platform_id: macos
            preset: release
            cmake_build_preset: release
            build_path: "build/release"

    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Linux dependencies
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libasound2-dev \
            libx11-dev \
            libxcomposite-dev \
            libxcursor-dev \
            libxinerama-dev \
            libxrandr-dev \
            libfreetype6-dev \
            libfontconfig1-dev \
            libgl1-mesa-dev \
            libwebkit2gtk-4.1-dev

      - name: Cache JUCE
        uses: actions/cache@v4
        id: cache-juce
        with:
          path: ${{ github.workspace }}/.juce_cache
          key: ${{ runner.os }}-juce-${{ hashFiles('**/CMakeLists.txt') }}

      - name: Configure CMake
        shell: bash
        run: |
          if [ "${{ matrix.os }}" == "macos-latest" ]; then
            # macOS requires Xcode generator for AU plugin support
            cmake -G Xcode -B ${{ matrix.build_path }} -DFETCHCONTENT_BASE_DIR=${{ github.workspace }}/.juce_cache
          else
            # Linux/Windows use presets
            cmake --preset=${{ matrix.preset }} -DFETCHCONTENT_BASE_DIR=${{ github.workspace }}/.juce_cache
          fi

      - name: Build with CMake
        run: cmake --build ${{ matrix.build_path }} --config Release

      - name: Validate build artifacts
        run: bash scripts/validate-builds.sh Release
        shell: bash

      - name: Extract plugin metadata
        id: plugin_meta
        shell: bash
        run: |
          source ${{ matrix.build_path }}/plugin_metadata.sh
          echo "product_name=$PROJECT_NAME_PRODUCT" >> $GITHUB_OUTPUT
          echo "version=$PROJECT_VERSION" >> $GITHUB_OUTPUT
          echo "target_name=$PROJECT_NAME_TARGET" >> $GITHUB_OUTPUT
          # Create sanitized name for ZIP file (replace spaces with hyphens)
          ZIP_NAME=$(echo "$PROJECT_NAME_PRODUCT" | sed 's/ /-/g')
          echo "zip_name=${ZIP_NAME}-${{ github.ref_name }}-${{ matrix.platform_id }}.zip" >> $GITHUB_OUTPUT

      - name: Archive plugin artifacts
        shell: bash
        run: |
          ARTIFACT_DIR="${{ matrix.build_path }}/${{ steps.plugin_meta.outputs.target_name }}_artefacts/Release"
          cd "$ARTIFACT_DIR"
          if [ "${{ matrix.os }}" == "macos-latest" ]; then
            zip -r "${{ github.workspace }}/${{ steps.plugin_meta.outputs.zip_name }}" VST3 Standalone AU
          else
            zip -r "${{ github.workspace }}/${{ steps.plugin_meta.outputs.zip_name }}" VST3 Standalone
          fi

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.plugin_meta.outputs.zip_name }}
          path: ${{ steps.plugin_meta.outputs.zip_name }}

  create_release:
    name: Create GitHub Release
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write # Required to create a release

    steps:
      - name: Download all build artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Create Release and Upload Assets
        uses: softprops/action-gh-release@v2
        with:
          files: artifacts/*/*.zip
          body: "Automated release for version ${{ github.ref_name }}."
          fail_on_unmatched_files: true
